# Zappr application configuration: opensource
ROBOT_AUTHENTICATION: apikey
APIKEYS:
  - "123"
  - "345"

# ROBOT_AUTHENTICATION: planb
# PLANB_TOKENINFO: ...

# path to zapprfile in repository
VALID_ZAPPR_FILE_PATHS:
  - "/.zappr.yaml"
  - "/.zappr.yml"
ZAPPR_DEFAULT_CONFIG:
  autobranch:
    pattern: "{number}-{title}"
    length: 60
  commit:
    message:
      patterns:
        - "^#[0-9]+"
  approvals:
    minimum: 2
    ignore: none
    pattern: "^(:\\+1:|👍)$"
    veto:
      # veto/blocking a PR = comment that matches this regex
      pattern: "^(:\\-1:|👎)$"
